DROP TABLE IF EXISTS element;
DROP TABLE IF EXISTS links;

CREATE TABLE element (
  id INT  PRIMARY KEY,
  type VARCHAR(1),
  width DECIMAL(10,2) ,
  height DECIMAL(10,2)
);

CREATE TABLE links (
  element_ID1 INT NOT NULL,
  element_ID2 INT NOT NULL,
  direction varchar(20) ,
  foreign key (element_ID1) references element(id),
  foreign key (element_ID2) references element(id)
);

INSERT INTO element (id, type, width, height) VALUES	(120,'B',NULL,30);
INSERT INTO element (id, type, width, height) VALUES	(121,'C',700,7);
INSERT INTO element (id, type, width, height) VALUES	(122,'L',2750,8);
INSERT INTO element (id, type, width, height) VALUES	(123,'L',3000,8);
INSERT INTO element (id, type, width, height) VALUES	(124,'C',5500,NULL);
INSERT INTO element (id, type, width, height) VALUES	(125,'L',8000,115);
INSERT INTO element (id, type, width, height) VALUES	(126,'L',7200,160);
INSERT INTO element (id, type, width, height) VALUES	(127,'C',510,NULL);
INSERT INTO element (id, type, width, height) VALUES	(128,'C',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(129,'C',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(130,'C',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(131,'C',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(132,NULL,7200,35);
INSERT INTO element (id, type, width, height) VALUES	(133,'C',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(134,'C',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(135,'C',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(136,'C',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(137,'C',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(138,'C',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(139,'C',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(142,'T',10000,NULL);
INSERT INTO element (id, type, width, height) VALUES	(143,'M',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(144,'C',180,NULL);
INSERT INTO element (id, type, width, height) VALUES	(145,'C',100,NULL);
INSERT INTO element (id, type, width, height) VALUES	(146,'C',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(147,'C',400,NULL);
INSERT INTO element (id, type, width, height) VALUES	(148,'C',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(149,'C',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(150,'L',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(151,'L',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(152,'S',920,NULL);
INSERT INTO element (id, type, width, height) VALUES	(153,'S',2000,NULL);
INSERT INTO element (id, type, width, height) VALUES	(154,'S',724,NULL);
INSERT INTO element (id, type, width, height) VALUES	(155,'S',1580,NULL);
INSERT INTO element (id, type, width, height) VALUES	(156,'S',250,NULL);
INSERT INTO element (id, type, width, height) VALUES	(157,'S',1185,NULL);
INSERT INTO element (id, type, width, height) VALUES	(158,'S',660,NULL);
INSERT INTO element (id, type, width, height) VALUES	(159,'S',1315,NULL);
INSERT INTO element (id, type, width, height) VALUES	(160,'S',1315,NULL);
INSERT INTO element (id, type, width, height) VALUES	(161,'S',2000,NULL);
INSERT INTO element (id, type, width, height) VALUES	(162,'M',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(163,'M',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(165,'M',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(166,'M',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(167,'M',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(314,'C',125,4.1);
INSERT INTO element (id, type, width, height) VALUES	(317,'C',320,10);
INSERT INTO element (id, type, width, height) VALUES	(332,'C',40,1.2);
INSERT INTO element (id, type, width, height) VALUES	(333,'C',90,1.4);
INSERT INTO element (id, type, width, height) VALUES	(334,'C',125,2.1);
INSERT INTO element (id, type, width, height) VALUES	(335,'C',102,2.5);
INSERT INTO element (id, type, width, height) VALUES	(336,'C',60,3);
INSERT INTO element (id, type, width, height) VALUES	(337,'C',180,1.6);
INSERT INTO element (id, type, width, height) VALUES	(338,'C',82,1.25);
INSERT INTO element (id, type, width, height) VALUES	(339,'C',80,1.2);
INSERT INTO element (id, type, width, height) VALUES	(340,'C',190,2.2);
INSERT INTO element (id, type, width, height) VALUES	(341,'C',280,2);
INSERT INTO element (id, type, width, height) VALUES	(342,'C',250,2.3);
INSERT INTO element (id, type, width, height) VALUES	(343,'C',320,2);
INSERT INTO element (id, type, width, height) VALUES	(344,'C',150,2);
INSERT INTO element (id, type, width, height) VALUES	(345,'C',300,1);
INSERT INTO element (id, type, width, height) VALUES	(346,'C',50,1.6);
INSERT INTO element (id, type, width, height) VALUES	(347,'C',70,1.25);
INSERT INTO element (id, type, width, height) VALUES	(348,'C',140,2.2);
INSERT INTO element (id, type, width, height) VALUES	(349,'C',130,1.8);
INSERT INTO element (id, type, width, height) VALUES	(350,'C',92,2.8);
INSERT INTO element (id, type, width, height) VALUES	(424,'C',NULL,31);
INSERT INTO element (id, type, width, height) VALUES	(425,'C',498,48);
INSERT INTO element (id, type, width, height) VALUES	(426,'C',NULL,35);
INSERT INTO element (id, type, width, height) VALUES	(428,'C',NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(429,'C',226,13.2);
INSERT INTO element (id, type, width, height) VALUES	(430,'C',153,9.9);
INSERT INTO element (id, type, width, height) VALUES	(431,'C',318,27.5);
INSERT INTO element (id, type, width, height) VALUES	(432,'C',275,24);
INSERT INTO element (id, type, width, height) VALUES	(433,'C',437,18);
INSERT INTO element (id, type, width, height) VALUES	(434,'C',460,23);
INSERT INTO element (id, type, width, height) VALUES	(435,'C',400,18);
INSERT INTO element (id, type, width, height) VALUES	(436,'M',61,26.5);
INSERT INTO element (id, type, width, height) VALUES	(437,'M',16,4.1);
INSERT INTO element (id, type, width, height) VALUES	(438,'M',43,12.25);
INSERT INTO element (id, type, width, height) VALUES	(439,'M',9,91.5);
INSERT INTO element (id, type, width, height) VALUES	(440,NULL,NULL,3.3);
INSERT INTO element (id, type, width, height) VALUES	(441,NULL,144,43.3);
INSERT INTO element (id, type, width, height) VALUES	(442,NULL,NULL,3.9);
INSERT INTO element (id, type, width, height) VALUES	(443,'C',NULL,4.4);
INSERT INTO element (id, type, width, height) VALUES	(444,'C',NULL,10.5);
INSERT INTO element (id, type, width, height) VALUES	(445,'C',NULL,12.6);
INSERT INTO element (id, type, width, height) VALUES	(446,'C',190,8.2);
INSERT INTO element (id, type, width, height) VALUES	(447,'C',115,55.3);
INSERT INTO element (id, type, width, height) VALUES	(448,'C',43,13.4);
INSERT INTO element (id, type, width, height) VALUES	(449,'C',335,37.8);
INSERT INTO element (id, type, width, height) VALUES	(450,'C',NULL,17);
INSERT INTO element (id, type, width, height) VALUES	(451,'C',160,26.7);
INSERT INTO element (id, type, width, height) VALUES	(452,'C',NULL,10.2);
INSERT INTO element (id, type, width, height) VALUES	(453,'C',30,21.5);
INSERT INTO element (id, type, width, height) VALUES	(454,'C',33,2.3);
INSERT INTO element (id, type, width, height) VALUES	(455,'C',115,15.3);
INSERT INTO element (id, type, width, height) VALUES	(456,'C',213,49.7);
INSERT INTO element (id, type, width, height) VALUES	(457,'C',142,27.8);
INSERT INTO element (id, type, width, height) VALUES	(458,'C',19,82.3);
INSERT INTO element (id, type, width, height) VALUES	(459,'C',248,310.2);
INSERT INTO element (id, type, width, height) VALUES	(460,'C',422,48.2);
INSERT INTO element (id, type, width, height) VALUES	(461,'C',372,83.5);
INSERT INTO element (id, type, width, height) VALUES	(462,'C',NULL,3.3);
INSERT INTO element (id, type, width, height) VALUES	(463,'C',NULL,3.4);
INSERT INTO element (id, type, width, height) VALUES	(464,'C',NULL,5.8);
INSERT INTO element (id, type, width, height) VALUES	(465,'C',NULL,4.8);
INSERT INTO element (id, type, width, height) VALUES	(466,'C',NULL,3.4);
INSERT INTO element (id, type, width, height) VALUES	(467,'C',NULL,2.9);
INSERT INTO element (id, type, width, height) VALUES	(468,'C',NULL,4.4);
INSERT INTO element (id, type, width, height) VALUES	(469,'C',NULL,2.4);
INSERT INTO element (id, type, width, height) VALUES	(470,'C',NULL,3.9);
INSERT INTO element (id, type, width, height) VALUES	(1369,NULL,NULL,NULL);
INSERT INTO element (id, type, width, height) VALUES	(1370,NULL,NULL,NULL);

insert into links (element_ID1, element_ID2, direction)  values	(314,317,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(332,333,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(333,334,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(334,337,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(335,336,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(335,338,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(336,339,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(336,341,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(337,338,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(337,340,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(338,339,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(339,340,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(340,341,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(341,342,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(341,342,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(341,343,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(342,343,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(343,344,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(343,345,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(344,345,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(346,347,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(347,348,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(348,349,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(349,350,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(121,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(121,123,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(122,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(122,121,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(122,121,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(122,124,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(122,127,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(122,127,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(122,128,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(122,128,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(122,129,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(122,130,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(122,130,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(122,133,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(122,134,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(122,1370,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(123,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(123,121,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(123,124,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(123,128,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(123,131,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(123,131,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(123,1369,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(124,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(124,122,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(124,122,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(124,123,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(124,126,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(124,134,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(125,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(125,124,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(125,132,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(125,133,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(125,134,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(125,135,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(125,136,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(125,137,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(125,138,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(125,139,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(125,152,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(125,154,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(125,156,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(125,158,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(125,160,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(126,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(127,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(127,122,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(128,121,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(128,122,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(128,123,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(128,123,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(129,122,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(129,123,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(129,123,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(129,128,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(130,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(130,122,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(131,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(131,123,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(132,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(132,125,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(133,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(134,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(135,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(135,153,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(136,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(136,155,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(137,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(137,157,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(138,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(138,159,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(139,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(139,161,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(142,143,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(142,144,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(142,145,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(142,146,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(142,148,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(142,149,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(142,150,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(143,150,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(144,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(144,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(144,142,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(145,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(145,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(145,142,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(145,142,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(145,147,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(146,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(146,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(146,142,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(146,145,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(147,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(147,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(147,151,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(148,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(148,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(148,142,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(148,143,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(148,147,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(149,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(149,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(149,142,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(149,142,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(149,143,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(149,148,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(150,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(150,147,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(151,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(151,142,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(152,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(152,135,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(153,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(153,125,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(154,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(154,136,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(155,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(155,125,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(156,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(156,137,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(157,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(157,125,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(158,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(158,138,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(159,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(159,125,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(160,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(160,139,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(161,120,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(161,125,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(162,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(163,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(163,162,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(165,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(165,167,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(166,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(167,120,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(167,165,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(424,425,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(424,442,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(425,424,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(425,426,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(425,426,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(425,460,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(425,462,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(428,429,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(428,439,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(428,442,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(428,443,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(428,446,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(429,425,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(429,428,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(429,431,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(429,449,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(430,428,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(430,431,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(430,432,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(430,449,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(431,430,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(431,432,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(431,432,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(431,438,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(431,440,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(431,446,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(431,447,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(431,453,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(431,453,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(431,454,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(431,455,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(431,455,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(431,456,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(432,428,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(432,433,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(432,442,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(432,460,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(432,462,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(433,434,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(433,434,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(433,466,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(434,433,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(434,435,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(434,435,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(434,468,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(436,425,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(436,431,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(436,445,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(436,449,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(437,450,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(438,432,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(438,450,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(438,456,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(439,428,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(439,457,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(440,426,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(440,433,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(440,434,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(440,460,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(440,464,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(441,459,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(442,433,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(442,462,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(443,428,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(443,445,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(444,443,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(444,445,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(444,445,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(445,428,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(445,431,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(445,436,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(445,436,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(445,449,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(446,428,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(446,431,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(446,447,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(447,432,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(447,448,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(447,456,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(448,432,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(448,438,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(448,456,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(448,456,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(449,430,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(449,430,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(449,446,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(449,447,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(449,450,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(450,432,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(450,432,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(450,437,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(450,438,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(450,449,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(450,451,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(450,451,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(450,452,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(450,455,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(450,456,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(451,432,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(451,432,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(451,437,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(451,450,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(451,452,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(451,453,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(451,454,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(451,455,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(452,432,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(452,432,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(452,440,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(452,453,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(453,440,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(453,454,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(454,440,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(454,455,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(455,440,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(455,441,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(455,441,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(455,456,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(455,456,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(456,439,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(456,441,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(456,457,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(457,428,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(457,441,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(457,458,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(457,459,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(458,428,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(458,459,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(459,426,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(459,433,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(459,441,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(459,442,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(459,458,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(459,460,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(459,462,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(460,425,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(460,432,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(460,459,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(460,461,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(460,462,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(460,465,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(461,462,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(461,462,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(462,463,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(463,466,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(464,433,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(464,460,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(464,465,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(465,433,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(465,461,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(465,463,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(465,466,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(466,433,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(466,435,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(466,463,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(466,467,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(466,468,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(467,435,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(467,468,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(467,468,'lateral');
insert into links (element_ID1, element_ID2, direction)  values	(468,469,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(468,470,'vertical');
insert into links (element_ID1, element_ID2, direction)  values	(469,470,'vertical');